project:
  type: website
  output-dir: docs

website:
  title: "astronautgabe.github.io"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: scrollytelling.html
        text: Transfer Portal Project

format:
  html:
    theme: 
      light: minty
      dark: solar
    css: styles.css
    toc: true

editor: visual

